# Generated by Django 4.1.5 on 2023-01-06 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CartApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carts',
        ),
    ]
